export const SET_REPOS_SELECTION = "SET_REPOS_SELECTION";
export const SET_WORKSPACE_SELECTION = "SET_WORKSPACE_SELECTION";
export const SET_REFRESH_MINS = "SET_REFRESH_MINS";
export const SET_SHOULD_DATA_REFRESH = "SET_SHOULD_DATA_REFRESH";
export const FETCH_WORKSPACES_BEGIN = "FETCH_WORKSPACES_BEGIN";
export const FETCH_WORKSPACES_SUCCESS = "FETCH_WORKSPACES_SUCCESS";
export const FETCH_WORKSPACES_FAILURE = "FETCH_WORKSPACES_FAILURE";