export const SET_REPOS_SELECTION = "SET_REPOS_SELECTION";
export const SET_WORKSPACE_SELECTION = "SET_WORKSPACE_SELECTION";
export const SET_REFRESH_MINS = "SET_REFRESH_MINS";
export const SET_SHOULD_DATA_REFRESH = "SET_SHOULD_DATA_REFRESH";